### ISSUE TITLE
Putting the Inbox secret into the app is a major security issue

### ISSUE THREAD

**Issue by guenard** [bamlab/react-native-batch-push#1]
**The Inbox secret** is not required to use the Inbox feature at the installation/device-level. It is only required [if you want to use the Inbox feature at the user-level](https://batch.com/doc/android/inbox.html#_custom-user-id-mode) (for example if you want a logged-in user to get notifications received on another device in an unified notification center).

And if you plan to use the Inbox at the user-level, the secret should still be kept private on your server and used to generate a hash that is then sent back to the app through your own webservice. If someone find your Inbox secret (eg: by reverse-engineering the app), he could read private notifications of all your logged-in users (assuming that he knows the user Custom ID).

On another note, thank you so much for your work on this React Native plugin!

**Comment by Minishlink** [comment]
Thanks @guenard, will update ASAP!
