### ISSUE TITLE
Allow to disable automatic mode using a boolean

### ISSUE THREAD

**Issue by ScreamZ** [bamlab/react-native-batch-push#10]
Hey,

I figured out that local notification conflict with batch in automatic mode, can we get 
`[BatchPush disableAutomaticIntegration];` hook that activate this before start ? Using a boolean in config ?

https://batch.com/doc/ios/advanced/manual-integration.html

Regards

**Comment by yleflour** [comment]
Hello, you need to do this manually in your AppDelegate.m
We currently don't have a way of doing through a bridge so I recommend following [this documentation](https://batch.com/doc/ios/advanced/manual-integration.html)
