### ISSUE TITLE
Failed to post notification on channel "null"

### ISSUE THREAD

**Issue by urapico** [bamlab/react-native-batch-push#12]
Hi! 😄 

Over Android 8.0 support notification channel.
> https://batch.com/doc/android/advanced/notification-channels.html#_custom-receivers

When I develop on SDK 27, I get error that is same to below page.

https://stackoverflow.com/questions/44489657/android-o-reporting-notification-not-posted-to-channel-but-it-is

Please tell me how to set it channel. :bow:

**Comment by marekkalnik** [comment]
Thanks @urapico  for your contribution. I'm closing this issue as Batch released a new version and this repository is being archived.

This should be addressed in https://github.com/BatchLabs/Batch-React-Native-Plugin
