### ISSUE TITLE
UserEditor not working as expected

### ISSUE THREAD

**Issue by jakobereksen** [bamlab/react-native-batch-push#21]
const editor = new BatchUserEditor(); 
    editor.setIdentifier('some_identifier');
    editor.save();

seems not add an setIdentfifier action in the js implementation, so when `editor.save();` is called, no action is passed to the native implementation. When the editor is initialized like this though:

    const editor = new BatchUserEditor([
      {
        type: 'setIdentifier',
        value: 'some_identifier'
      }
    ]);
    editor.save();

The identifier is set as expected.

**Comment by abarisain** [comment]
Hello,

Could you try chaining the calls?

https://github.com/bamlab/react-native-batch-push/blob/master/src/BatchUserEditor.ts#L86 shows that you should either chain the calls, or reassign editor on each call.

**Comment by jakobereksen** [comment]
Thank you, you are right.
