### ISSUE TITLE
Support Android X

### ISSUE THREAD

**Issue by WoodyWoodsta** [bamlab/react-native-batch-push#22]
To fix dependency on deprecated support libraries:

```java
"error: package android.support.annotation does not exist:"

import android.support.annotation.NonNull;
                                 ^
```

**Comment by WoodyWoodsta** [comment]
Closing this, as upgrading to v4.x appeared to solve build issues in RN >= 0.60

**Comment by WoodyWoodsta** [comment]
Re-opening as this is, in fact, still something that needs to be done.

**Comment by Minishlink** [comment]
Use jetifier in the meantime

**Comment by WoodyWoodsta** [comment]
Due to a pretty blurry limitation of Jetifier, some dependencies aren't patched by the tool. It appears this one isn't, and I'm unable to figure out why.

**Comment by abarisain** [comment]
Doesn’t jetifier only work on precompiled libraries rather than ones included by source?

**Comment by Minishlink** [comment]
Yes sorry I was talking about this jetifier https://github.com/mikehardy/jetifier

**Comment by Minishlink** [comment]
Published https://github.com/bamlab/react-native-batch-push/releases/tag/v5.0.0

**Comment by WoodyWoodsta** [comment]
Thanks guys!
