### ISSUE TITLE
Module RNBatch requires main queue setup since it overrides `init`

### ISSUE THREAD

**Issue by martinfrouin** [bamlab/react-native-batch-push#26]
I've got this warning message after just implementing the module:

`Module RNBatch requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

Is there a workaround ?

**Comment by Minishlink** [comment]
Hello, this has been fixed in v5.0.2. Please upgrade and let me know if anything is wrong.
