### ISSUE TITLE
Swizzling causing Firebase to stop working

### ISSUE THREAD

**Issue by jyliang** [bamlab/react-native-batch-push#27]
**Environment:**
iOS 13.2
"@bam.tech/react-native-batch": "^5.0.1"
"react-native-firebase": "5.2.2"

**Error from Firebase:**
Error: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotification: method.

**Guess**
Conflict is caused by Batch's swizzling methods and Firebase's swizzling methods.

**Comment by Minishlink** [comment]
Hi @jyliang, this is not an issue with this React Native bridge. Please contact directly the Batch support

Also, https://doc.batch.com/ios/advanced/manual-integration ...
