### ISSUE TITLE
No notifications on iOS & Android

### ISSUE THREAD

**Issue by martinfrouin** [bamlab/react-native-batch-push#32]
I don't have any notifications (on iOS & Android) since I switched to this package. (I was using `dangerfarms/react-native-batch`)
Is there anything special to configure?

When i'm testing the push notifications with my device installation id it's working normally.

Currently, I'm just doing a `Batch.start()` at the launch of my app.

Here's the version i'm using
```
"@bam.tech/react-native-batch": "^5.0.2",
"react-native": "0.61.4",
```

Thanks

**Comment by martinfrouin** [comment]
I think it's because my customer id is empty. I don't really understand how to use `BatchUserEditor.setIdentifier`.

When I do something like
```
BatchUserEditor.setIdentifier('test')
BatchUserEditor.save()
```
I have this error : `undefined is not an object evaluating BatchUserEditor.setIdentifier`

**Comment by abarisain** [comment]
Hi,

BatchUserEditor is a class that:
 - You must get an instance of
 - You must keep that same instance and call save on it

For example:

A valid call is:
```
BatchUser.editor().setIdentifier("test").save();
```

An INVALID call would be:
```
BatchUser.editor().setIdentifier("testapp");
BatchUser.editor().save();
```
This doesn't work as the editor batches changes locally, and thus nothing will be saved.

**Comment by martinfrouin** [comment]
Thank you !

You should improve your README with examples :-)
