### ISSUE TITLE
[DOC] RNBatchPush.loginUser got 0 arguments, expected 1

### ISSUE THREAD

**Issue by henricazottes** [bamlab/react-native-batch-push#9]
Hi,

Your README states:
```Javascript
// if you want to give a custom identifier to the user
BatchPush.loginUser('theUserId');
```

 My understanding was that it's not mandatory to give a custom ID. However, if I call ``BatchPush.login()`` without one I get this error:
```Javascript
RNBatchPush.loginUser got 0 arguments, expected 1
```
Which goes away when I set one. Could you update the doc for that ?

**Comment by Minishlink** [comment]
Thanks for the feedback, the doc is updated.

As the flow typing indicates, the `loginUser` function takes a string argument.
